# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-09 06:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sender', models.IntegerField()),
                ('target', models.IntegerField()),
                ('title', models.CharField(max_length=256)),
                ('content', models.TextField(default='\u6682\u65e0\u7b80\u4ecb')),
                ('isRead', models.BooleanField(default=False)),
                ('createTime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationController',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('userId', models.IntegerField()),
                ('unReadCount', models.IntegerField(default=0)),
            ],
        ),
    ]
