# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-02 05:48
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=256)),
                ('desc', models.TextField(default='\u6682\u65e0\u7b80\u4ecb')),
                ('timeRegSt', models.DateTimeField(default=django.utils.timezone.now)),
                ('timeRegEn', models.DateTimeField(default=django.utils.timezone.now)),
                ('timeEvnSt', models.DateTimeField(default=django.utils.timezone.now)),
                ('timeEvnEn', models.DateTimeField(default=django.utils.timezone.now)),
                ('maxRegCnt', models.IntegerField(default=-1)),
                ('nowRegCnt', models.IntegerField(default=0)),
                ('teamMode', models.IntegerField(default=0)),
                ('teamMin', models.IntegerField(null=True)),
                ('teamMax', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Signs',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('eventId', models.IntegerField(null=True)),
                ('userId', models.IntegerField(null=True)),
                ('teamSize', models.IntegerField(default=1)),
                ('teamMate', models.CharField(max_length=256, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('timeReg', models.DateTimeField(default=django.utils.timezone.now)),
                ('exmTime', models.DateTimeField(null=True)),
                ('exmStatus', models.IntegerField(default=1)),
                ('score', models.CharField(max_length=256, null=True)),
                ('prize', models.CharField(default='0', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('authority', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=32, null=True)),
                ('fullname', models.CharField(max_length=32, null=True)),
                ('certification_type', models.IntegerField(default=0)),
                ('certification_id', models.CharField(max_length=32, null=True)),
                ('mobile', models.CharField(max_length=32, null=True)),
                ('classnumber', models.CharField(max_length=32, null=True)),
                ('email', models.CharField(max_length=32, null=True)),
                ('student_number', models.CharField(max_length=32, null=True)),
                ('birthday', models.CharField(max_length=32, null=True)),
                ('room_address', models.CharField(max_length=32, null=True)),
                ('cloth_size', models.CharField(choices=[('S', 'Small'), ('M', 'Middle'), ('L', 'Large')], max_length=1, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('degree', models.IntegerField(null=True)),
            ],
        ),
    ]
