# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IMG',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to='img')),
                ('name', models.CharField(max_length=20)),
                ('detail', models.TextField(default='\u6682\u65e0')),
                ('imgtype', models.IntegerField(default=0)),
            ],
        ),
    ]
