# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0003_events_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='classNumber',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
