# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0004_auto_20171025_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='authority',
            field=models.IntegerField(default=0),
        ),
    ]
