# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 04:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0004_auto_20171025_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='classNumber',
        ),
        migrations.AddField(
            model_name='sign',
            name='prize',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='sign',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='sign',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='authority',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='classnumber',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='fullname',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
