# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-10-31 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0005_auto_20171026_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(null=True, unique_for_date=True),
        ),
        migrations.AddField(
            model_name='user',
            name='certification_id',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='certification_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='cloth_size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Middle'), ('L', 'Large')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='degree',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='room_address',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='student_number',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
