# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0006_auto_20171025_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='classNumber',
        ),
        migrations.AddField(
            model_name='user',
            name='classnumber',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
