# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-01 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0006_auto_20171031_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
