# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0007_auto_20171025_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='sign',
            name='prize',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
