# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0008_sign_prize'),
    ]

    operations = [
        migrations.AddField(
            model_name='sign',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
