# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 02:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0011_auto_20171025_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='sign',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
