# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 03:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0011_auto_20171025_2038'),
        ('HomePage', '0005_sign_result'),
    ]

    operations = [
    ]
